import type { Metadata } from "next";
import "../globals.css";
import 'maplibre-gl/dist/maplibre-gl.css';
import NavItems from "@/components/nav/navItems";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <div style={{
        position: 'absolute',
        top: 0,
        right: 0,
        display: 'flex',
        justifyContent: 'flex-end',
        paddingRight: 20,
        paddingTop: 20,
        paddingBottom: 20,
      }}>
        <NavItems />

      </div>

      {children}
    </>
  );
}
