import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Head from "next/head";
import 'maplibre-gl/dist/maplibre-gl.css';
import { open_sans } from '@/ui/fonts';
import Footer from "@/components/footer";
import Link from "next/link";
import NavItems from "@/components/nav/navItems";


// import "../styles/global.scss"; // Import your SCSS file here

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
        {/* Start NavBar */}
        <div style={{
          display: 'flex',
          justifyContent: 'flex-end',
          paddingRight: 20,
          paddingTop: 20,
          paddingBottom: 20,
          background: '#009F9D'
        }}>
         <NavItems />

        </div>
        {/* End NavBar */}
        {/* <div style={{paddingLeft: 40, paddingRight: 40}}> */}
          {children}
    </>
  );
}
